spring:
  application:
    name: futbol

  datasource:
    url: jdbc:mysql://localhost:3306/football_training
    username: root
    password: Di1004960034.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      "[format_sql]": true

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    "[org.springframework]":  INFO

security:
  jwt:
    secret-key: mWOWGtEqOGvHmU2F3ri/Zsmt4/Q3yTnDeZG7+diVu3B19hK/dpfafFI/V65TGlECtCuzJ579QYBZu0K4ZaQMew==
    token-expiration: 6000000